import { readFileSync, writeFileSync } from "node:fs";
import { gzipSync } from "node:zlib";
import { fileURLToPath } from "node:url";
import ts from "typescript";

const root = new URL("../", import.meta.url);
// Reuse the application's aliases; the type-only Place import disappears during transpilation.
const source = readFileSync(new URL("src/lib/provinces.ts", root), "utf8");
const js = ts.transpileModule(source, { compilerOptions: { module: ts.ModuleKind.ESNext } }).outputText;
const { provinceIdFromShapeName } = await import(`data:text/javascript;base64,${Buffer.from(js).toString("base64")}`);
const geo = JSON.parse(readFileSync(new URL("public/data/th-provinces-adm1.geojson", root), "utf8"));
const polygons = (feature) => feature.geometry.type === "Polygon" ? [feature.geometry.coordinates] : feature.geometry.coordinates;
const points = geo.features.flatMap((feature) => polygons(feature).flat(2));
const west = Math.min(...points.map((p) => p[0]));
const east = Math.max(...points.map((p) => p[0]));
const south = Math.min(...points.map((p) => p[1]));
const north = Math.max(...points.map((p) => p[1]));
const projection = { west, north, cosLat: Math.cos((south + north) / 2 * Math.PI / 180), scale: 40 };
const project = ([lon, lat]) => [(lon - west) * projection.cosLat * projection.scale, (north - lat) * projection.scale];
const round = (n) => Number(n.toFixed(2));
const key = (p) => p.join(",");
const neighbours = new Map();
for (const feature of geo.features) for (const polygon of polygons(feature)) for (const ring of polygon) {
  for (let i = 1; i < ring.length; i++) {
    for (const [a, b] of [[ring[i - 1], ring[i]], [ring[i], ring[i - 1]]]) {
      if (!neighbours.has(key(a))) neighbours.set(key(a), new Set());
      neighbours.get(key(a)).add(key(b));
    }
  }
}
function simplify(line, tolerance = 0.45) {
  if (line.length <= 2) return line;
  const [a, b] = [line[0], line.at(-1)];
  const dx = b[0] - a[0], dy = b[1] - a[1], length = dx * dx + dy * dy;
  let best = tolerance * tolerance, at = -1;
  for (let i = 1; i < line.length - 1; i++) {
    const p = line[i];
    const t = length ? Math.max(0, Math.min(1, ((p[0] - a[0]) * dx + (p[1] - a[1]) * dy) / length)) : 0;
    const distance = (p[0] - a[0] - t * dx) ** 2 + (p[1] - a[1] - t * dy) ** 2;
    if (distance > best) { best = distance; at = i; }
  }
  return at < 0 ? [a, b] : [...simplify(line.slice(0, at + 1), tolerance).slice(0, -1), ...simplify(line.slice(at), tolerance)];
}
function ringPath(ring) {
  // Split at shared-boundary junctions so neighbouring provinces simplify the same arcs.
  const cuts = ring.slice(0, -1).flatMap((p, i) => neighbours.get(key(p)).size !== 2 ? [i] : []);
  if (cuts.length < 2) cuts.push(0, Math.floor((ring.length - 1) / 2));
  const unique = [...new Set(cuts)].sort((a, b) => a - b);
  const open = ring.slice(0, -1), result = [];
  for (let i = 0; i < unique.length; i++) {
    const start = unique[i], end = unique[(i + 1) % unique.length];
    const arc = (end > start ? open.slice(start, end + 1) : [...open.slice(start), ...open.slice(0, end + 1)]).map(project);
    // Canonical direction also makes Douglas–Peucker tie-breaking identical on both sides.
    const reverse = key(arc[0]) > key(arc.at(-1));
    const reduced = simplify(reverse ? arc.toReversed() : arc);
    result.push(...(reverse ? reduced.toReversed() : reduced).slice(0, -1));
  }
  if (result.length < 3) return ringPathTriangle(ring);
  return `M${result.map((p) => p.map(round).join(",")).join("L")}Z`;
}
function ringPathTriangle(ring) {
  const open = ring.slice(0, -1);
  return `M${[0, Math.floor(open.length / 3), Math.floor(open.length * 2 / 3)].map((i) => project(open[i]).map(round).join(",")).join("L")}Z`;
}
const entries = geo.features.map((feature) => {
  const id = provinceIdFromShapeName(feature.properties.shapeName);
  if (!id) throw new Error(`Unmatched province: ${feature.properties.shapeName}`);
  const coordinates = polygons(feature).flat(2).map(project);
  const xs = coordinates.map((p) => p[0]), ys = coordinates.map((p) => p[1]);
  return { id, d: polygons(feature).map((polygon) => polygon.map(ringPath).join("")).join(""),
    cx: round((Math.min(...xs) + Math.max(...xs)) / 2), cy: round((Math.min(...ys) + Math.max(...ys)) / 2) };
}).sort((a, b) => a.id.localeCompare(b.id, "en"));
if (entries.length !== 77 || new Set(entries.map((p) => p.id)).size !== 77) throw new Error("Expected 77 distinct provinces");
const viewBox = `-4 -4 ${round((east - west) * projection.cosLat * projection.scale + 8)} ${round((north - south) * projection.scale + 8)}`;
const output = `// Generated by scripts/build-th-svg.mjs; do not edit.\nexport const thProjection = ${JSON.stringify(projection)};\nexport const thViewBox = ${JSON.stringify(viewBox)};\nexport const thAttribution = "geoBoundaries / © OpenStreetMap contributors (ODbL)";\nexport const thProvinces = [\n${entries.map((entry) => `  ${JSON.stringify(entry)},`).join("\n")}\n];\n`;
const bytes = gzipSync(output).length;
if (bytes > 40 * 1024) throw new Error(`Thailand SVG exceeds 40 KB gzip: ${bytes}`);
const target = fileURLToPath(new URL("src/lib/visuals/th-provinces.ts", root));
if (process.argv.includes("--check")) {
  if (readFileSync(target, "utf8") !== output) throw new Error("Thailand SVG is stale; run node scripts/build-th-svg.mjs");
} else writeFileSync(target, output);
console.log(`Thailand SVG: ${entries.length} paths, ${bytes} bytes gzip${process.argv.includes("--check") ? ", matches generated file" : ""}`);
